### ISSUE TITLE
Support Gnome 3.14

### ISSUE THREAD

**Issue by ivoarch** [abihf/adwaita-compact#2]
Please add support for CentOS 7 (Gnome v3.14) .
Thanks!!

**Comment by abihf** [comment]
I'm sorry, there are many incompatibilities between 3.14 and 3.20 and I use arch linux which always use latest version of gnome.
But, why are you still using 2 years old DE?

**Comment by ivoarch** [comment]
Because I use centos linux which use version 3.14 :smile:
