### ISSUE TITLE
nautilus sidebar items spacing still too big

### ISSUE THREAD

**Issue by corebots** [abihf/adwaita-compact#3]
First of all I want to thank you guys for all this work on 'fixing' the default theme :) Adwaita feels much better now. 

However, I'd like to suggest a reduction of padding/spacing for the sidebar items, used for example by Nautilus. I assume you've kept the 'line-height' of the sidebar at default, which now seems too high when comparing it to other parts the theme you've made more compact. all the gray space between the lines now glows and asks for pixel-optimalization :) Could you do something about it?

**Comment by abihf** [comment]
hi @corebots 

sorry for late response. I agree with you that the height of sidebar items should be reduced. i will update this soon

**Comment by abihf** [comment]
hi @corebots

sorry for late response. I agree with you that the height of sidebar items should be reduced. i will update this soon
![nautilus](https://cloud.githubusercontent.com/assets/1484485/18339109/be0e9460-75c7-11e6-93c5-bdaa8ae5b80e.png)

**Comment by corebots** [comment]
Thank you! I'm also now looking at the right side of the window - the folder list, at its smaller size, could also use some line height reduction.
![wluan9x](https://cloud.githubusercontent.com/assets/12252430/18454866/1272389a-7947-11e6-8831-532e73afd423.png)

**Comment by corebots** [comment]
It appears that when I change the interface font the lineheight changes too. Sorry I have little knowledge about theming :)
![tve3shm](https://cloud.githubusercontent.com/assets/12252430/18455712/fdaa8bb0-794b-11e6-9cda-26e596a46525.png)

**Comment by abihf** [comment]
try this: 

``` css
placessidebar row {
  min-height: 26px;
}

placessidebar row > revealer {
    padding: 0 8px; 
}
```

**Comment by abihf** [comment]
i have updated this theme here https://github.com/abihf/adwaita-compact/commit/cd60a05e9a7af8d4f2bbaaf3c2cc6808c59fff73#diff-0cbb953abef8225716598d0e96a50952R3668 

you can download latest theme from https://github.com/abihf/adwaita-compact/archive/v3.20.9.1.tar.gz

**Comment by corebots** [comment]
yes this works and looks much better now thank you! :) 
could you tell me which one is the property to increase the distance between the sidebar icons and the left window border please? I’d like to try to move them 1 or 2px to the right. is there any documentation to tell you which property does what? or you have to do it by trial/error? thanks

**Comment by abihf** [comment]
I use `GTK3_DEBUG=interactive` for trying css. 

To move the icon, i use padding on revealer. you can look at here https://github.com/abihf/adwaita-compact/blob/master/gtk-3.0/_common.scss#L3673
