### ISSUE TITLE
Updating to GTK/GNOME 3.24?

### ISSUE THREAD

**Issue by 38github** [abihf/adwaita-compact#7]
Has work on updating your modified theme to GNOME 3.24 begun? Is it also possible to send you a few dollars to encourage your work?

Regards

**Comment by ghost** [comment]
@38github You may be interested to know that there is a mighty fine continuation going on over here:

https://github.com/godlyranchdressing/Minwaita

**Comment by abihf** [comment]
Hi @38github I'm sorry I don't have time to do it. Maybe you wanna give few dollars to Minwaita project.
And thanks @ainola for your info.

I will update the description to use Minwaita instead.
